# Generated by Django 3.2.6 on 2021-08-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSI_55_15_MIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=100, verbose_name='SYMBOL')),
                ('indicate', models.CharField(max_length=100, verbose_name='INDICATE')),
                ('type', models.CharField(max_length=100, verbose_name='TYPE')),
                ('close', models.FloatField(verbose_name='PRICE')),
                ('stoploss', models.FloatField(verbose_name='STOPLOSS')),
                ('rsi', models.FloatField(verbose_name='RSI')),
                ('rsi_exit_target', models.FloatField(blank=True, default=None, null=True, verbose_name='RSI_TARGET')),
                ('difference', models.FloatField(blank=True, default=None, null=True, verbose_name='PRICE DIFFERENCE')),
                ('profit', models.FloatField(blank=True, default=None, null=True, verbose_name='PROFIT (%)')),
            ],
            options={
                'db_table': 'RSI_55_15_MIN',
            },
        ),
        migrations.CreateModel(
            name='RSI_55_5_MIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=100, verbose_name='SYMBOL')),
                ('indicate', models.CharField(max_length=100, verbose_name='INDICATE')),
                ('type', models.CharField(max_length=100, verbose_name='TYPE')),
                ('close', models.FloatField(verbose_name='PRICE')),
                ('stoploss', models.FloatField(verbose_name='STOPLOSS')),
                ('rsi', models.FloatField(verbose_name='RSI')),
                ('rsi_exit_target', models.FloatField(blank=True, default=None, null=True, verbose_name='RSI_TARGET')),
                ('difference', models.FloatField(blank=True, default=None, null=True, verbose_name='PRICE DIFFERENCE')),
                ('profit', models.FloatField(blank=True, default=None, null=True, verbose_name='PROFIT (%)')),
            ],
            options={
                'db_table': 'RSI_55_5_MIN',
            },
        ),
    ]
